### signUp
POST http://localhost:3001/api/v1/auth/signup
Content-Type: application/json

{   
    "name": "Zé Prikito",
    "email": "ze@prikito.com",
    "password": "aicalica",
}

### signIn
POST http://localhost:3001/api/v1/auth/signin
Content-Type: application/json

{ 
    "email": "ze@prikito.com",
    "password": "aicalica"
}

### items user
POST   http://localhost:3001/api/v1/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlrDqSBQcmlraXRvIiwiZW1haWwiOiJ6ZUBwcmlraXRvLmNvbSIsInN1YiI6NCwicm9sZSI6WyJhZG1pbiJdLCJpYXQiOjE3NjIxMzA4MDMsImV4cCI6MTc2MjczNTYwM30.w3-_-GFQ7MR-Aijt0Nf2p3zIfhX-tGH4i45tjuzk2mA

### items user
GET   http://localhost:3001/api/v1/items

### scrap
POST   http://localhost:3001/api/v1/scrape
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlrDqSBQcmlraXRvIiwiZW1haWwiOiJ6ZUBwcmlraXRvLmNvbSIsInN1YiI6NCwicm9sZSI6WyJhZG1pbiJdLCJpYXQiOjE3NjIxMzA4MDMsImV4cCI6MTc2MjczNTYwM30.w3-_-GFQ7MR-Aijt0Nf2p3zIfhX-tGH4i45tjuzk2mA

{
    "site":"weworkremotely"
}

### criar item
POST http://localhost:3001/api/v1/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlrDqSBQcmlraXRvIiwiZW1haWwiOiJ6ZUBwcmlraXRvLmNvbSIsInN1YiI6NCwicm9sZSI6WyJhZG1pbiJdLCJpYXQiOjE3NjE5Njc3NDcsImV4cCI6MTc2MjU3MjU0N30.sxNBn5U4bYSp3YJAUchdW2vuwnaTtV91mF09mPVzf1c

{
    "position": "Desenvolvedor Fullstack",
    "company": "Acme Corp",
    "location": "Remoto",
    "salary": "R$8000",
    "post_link": "https://remoteok.com/job/123",
    "skills": ["JavaScript", "NestJS", "TypeORM"],
    "post_date": "2025-11-01T00:00:00.000Z",
    "source": "remoteok"
}

### listar item
GET http://localhost:3001/api/v1/items?page=1&pageSize=10&source=remoteOk&query=developer

###  detalhes
DELETE  http://localhost:3001/api/v1/items/824


### update item 
PUT http://localhost:3001/api/v1/items/822
Content-Type: application/json

{
    "position": "Desenvolvedor Backend Senior",
    "salary": "R$9500"
}

###
GET http://localhost:3001/api/v1/items