### signUp
POST http://localhost:3001/api/v1/auth/signup
Content-Type: application/json

{   "name": "Zé Prikito",
    "email": "ze@prikito.com",
    "password": "aicalica",
    "is_adm": false
}

### signIn
POST http://localhost:3001/api/v1/auth/signin
Content-Type: application/json

{ 
    "email": "ze@prikito.com",
    "password": "aicalica"
}